### ISSUE TITLE
Cannot scan `polkadot` chain

### ISSUE THREAD

**Issue by chenzongxiong** [opensquare-network/dotreasury#625]
`cd packages/scan && node src/index`

I received the following errors:

```
2021-05-30 06:46:50        RPC-CORE: getStorage(key: StorageKey, at?: BlockHash): StorageData:: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","refcount":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)
Error with block scan 1 Error: Unable to decode storage system.account:: createType(AccountInfo):: {"nonce":"Index","refcount":"RefCount","data":"AccountData"}:: Decoded input doesn't match input, received 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (80 bytes), created 0x0000000000000000000000000000000000000000000000000000000000000000…0000000000000000000000000000000000000000000000000000000000000000 (69 bytes)
    at RpcCore._newType (/Users/zxchen/litentry/dotreasury/node_modules/@polkadot/rpc-core/index.cjs:457:13)
    at RpcCore._formatStorageData (/Users/zxchen/litentry/dotreasury/node_modules/@polkadot/rpc-core/index.cjs:391:17)
    at RpcCore._formatOutput (/Users/zxchen/litentry/dotreasury/node_modules/@polkadot/rpc-core/index.cjs:368:19)
    at callWithRegistry (/Users/zxchen/litentry/dotreasury/node_modules/@polkadot/rpc-core/index.cjs:247:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

And I found it results from the following source code
https://github.com/opensquare-network/dotreasury/blob/main/packages/scan/src/utils/index.js#L113
```
    await api.query.system.account.at(blockHash, TreasuryAccount)
```

I also think the `TreasuryAccount` (DotTreasuryAccount) should be configured if we change from `kusama` to `polkadot`.

**Comment by wliyongfeng** [comment]
Fixed, please check the latest code.
